# TheAgenticCoder navigation menu
# Hub for vibe, spec, and agentic coders

[[main]]
  name = "Home"
  url = "/"
  weight = -112

[[main]]
  name = "News"
  url = "/categories/news/"
  weight = -110

[[main]]
  name = "How-Tos"
  url = "/categories/how-tos/"
  weight = -108

[[main]]
  name = "Videos"
  url = "/categories/videos/"
  weight = -106

[[main]]
  name = "Tools"
  identifier = "Tools"
  url = "/categories/tools/"
  weight = -104

[[main]]
  name = "Resources"
  url = "/categories/resources/"
  weight = -102

# [[main]]
#   name = "About"
#   url = "about/"
#   weight = -100

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/tonykay"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/cloud_assembler"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/tonykay"
[[social]]
  name = "youtube"
  weight = 4
  url = "https://www.youtube.com/@tonykay" # TODO: confirm YouTube channel URL
[[social]]
  name = "rss"
  weight = 5
  url = "index.xml"
